name: UnityBuildTest

on:
  workflow_dispatch:

permissions: write-all
  
jobs:
  buildForAndroid: 
    name: Build Android
    runs-on: ubuntu-latest
    steps:

      # Step 1 - Check Out
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Step 2 - Cache Library
      - name: Cache Library
        uses: actions/cache@v4
        with: 
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Step 3 - Free up disk space
      - name: Free Disk Space for Android
        run: |
          sudo swapoff -a || true
          sudo rm -f /swapfile || true
          sudo apt clean || true
          docker rmi "$(docker images -q)" || true
          df -h
          
      # Step 4 - Create Build Directory
      - name: Create Build Directory
        run: mkdir -p Builds/Android

      # Step 5 - Unity Build
      - name: Unity Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          projectPath: .
          buildName: TestProject
          buildsPath: Builds/Android
          allowDirtyBuild: true

      # Step 6 - Upload Build File
      - name: Upload Build File
        uses: actions/upload-artifact@v4
        with:
          name: TestProject
          path: Builds/Android
